framework:
    # Padrão: <2 chars para idioma (min)>_<2 chars para país (maiús)>.
    default_locale: pt_BR 
    translator:
        # Onde fica o diretório com as traduções.
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
